export const REGISTRATION_COUNTRY_OPTIONS = [
  'Argentina',
  'Australia',
  'Austria',
  'Belgium',
  'Brazil',
  'Bulgaria',
  'Canada',
  'Chile',
  'Croatia',
  'Czechia',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hungary',
  'India',
  'Ireland',
  'Italy',
  'Japan',
  'Mexico',
  'Netherlands',
  'New Zealand',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'Spain',
  'Sweden',
  'Switzerland',
  'United Kingdom',
  'United States',
] as const;

export const REGISTRATION_TIMEZONE_OPTIONS = [
  'UTC',
  'Africa/Cairo',
  'Africa/Johannesburg',
  'America/Argentina/Buenos_Aires',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Mexico_City',
  'America/New_York',
  'America/Sao_Paulo',
  'America/Toronto',
  'Asia/Dubai',
  'Asia/Kolkata',
  'Asia/Singapore',
  'Asia/Tokyo',
  'Australia/Melbourne',
  'Australia/Sydney',
  'Europe/Amsterdam',
  'Europe/Berlin',
  'Europe/Budapest',
  'Europe/Lisbon',
  'Europe/London',
  'Europe/Madrid',
  'Europe/Paris',
  'Europe/Rome',
  'Europe/Stockholm',
] as const;

export function isRegistrationCountry(value: string): boolean {
  return REGISTRATION_COUNTRY_OPTIONS.includes(value as (typeof REGISTRATION_COUNTRY_OPTIONS)[number]);
}

export function isRegistrationTimezone(value: string): boolean {
  return REGISTRATION_TIMEZONE_OPTIONS.includes(value as (typeof REGISTRATION_TIMEZONE_OPTIONS)[number]);
}
