import { randomUUID } from 'node:crypto';
import prisma, { Visibility, Prisma } from '@/lib/prisma';
import { decryptHighRiskContent } from '@/lib/high-risk-content-crypto';

const DIRECT_MESSAGE_ENCRYPTION_CONTEXT = 'changemappers:direct-message:v1';

function decryptDirectMessageRows<T extends { content?: string | null }>(messages: T[]): T[] {
  return messages.map((message) => {
    if (typeof message.content !== 'string') {
      return message;
    }
    return { ...message, content: decryptHighRiskContent(message.content, DIRECT_MESSAGE_ENCRYPTION_CONTEXT) };
  });
}

type GdprPrismaClient = typeof prisma;

export const GDPR_USER_RELATION_COVERAGE = [
  'AuditLog',
  'createdBacklogItems',
  'BacklogResonance',
  'Board',
  'CanvasNodeComment',
  'CoachMeConsent',
  'CoachMeSession',
  'CoachingOffer',
  'CoachingRequest',
  'claimedCommunities',
  'ownedCommunities',
  'communityMemberships',
  'CompassProfile',
  'receivedConnections',
  'sentConnections',
  'ContributionOffer',
  'ContributionRequest',
  'EnergyCanvas',
  'EnergyEntity',
  'EnergyPatternEntry',
  'EnergyRelation',
  'claimedEvents',
  'hostedEvents',
  'eventRsvps',
  'eventOrganizerRoles',
  'FeedComment',
  'FeedCommentReaction',
  'FeedPostReaction',
  'FeedPostRdgAnnotation',
  'FeedPostTagAnnotation',
  'FeedMention',
  'FeedPost',
  'Feedback',
  'ideaPosts',
  'ideaVotes',
  'ideaComments',
  'CaseWithProvenance',
  'ForwardReciprocityPrompt',
  'assignedInitiatives',
  'createdInitiatives',
  'InitiativeRole',
  'InitiativeUpdate',
  'InterventionRecord',
  'createdInvites',
  'receivedInvites',
  'revokedInvites',
  'IssueDispute',
  'IssueVouch',
  'givenAppreciations',
  'receivedAppreciations',
  'MatchRejectionLog',
  'MentorProfile',
  'MentoringRequest',
  'receivedMessages',
  'sentMessages',
  'refreshTokenSessions',
  'twoFactorBackupCodes',
  'sentNotifications',
  'Notification',
  'PageVisitLog',
  'PatternLibraryEntry',
  'PeerSupportOffer',
  'PeerSupportRequest',
  'Pitch',
  'PitchEndorsement',
  'ProjectReflection',
  'ReflectionRecord',
  'filedReports',
  'targetedReports',
  'RootCauseDiagnostic',
  'SavedVolunteerOpportunity',
  'SchedulingPoll',
  'SchedulingResponse',
  'Story',
  'StoryComment',
  'SocialIssue',
  'SystemsCanvas',
  'SystemsCanvasNode',
  'invitedBy',
  'TrainingOffer',
  'TrainingRequest',
  'invitedUsers',
  'functionalProfile',
  'interests',
  'onboardingState',
  'onboardingJourneySteps',
  'skills',
  'values',
  'VolunteerApplication',
  'VolunteerOpportunity',
  'interestedCauses',
  'mainCauses',
  'managedCauses',
  'weakSignals',
  'signalResonanceVotes',
  'signalCorroborations',
  'weakSignalPatterns',
  'signalCollections',
  'signalCollectionItems',
  'signalProjectLinks',
  'signalCommunityLinks',
  'announcementAcks',
] as const;

export const GDPR_USER_DATA_INVENTORY = [
  'account.profile',
  'account.functionalProfile',
  'account.onboardingState',
  'account.skills',
  'account.values',
  'account.interests',
  'communications.directMessages',
  'communications.notifications',
  'communications.invitations',
  'social.connections',
  'social.feedPosts',
  'social.feedComments',
  'social.feedReactions',
  'social.feedAnnotations',
  'social.feedMentions',
  'projects.pitches',
  'support.coachMeConsent',
  'support.coachMeSessions',
  'communities.memberships',
  'events.rsvps',
  'events.organizerRoles',
  'scheduling.polls',
  'scheduling.responses',
  'trust.reports',
  'operations.auditLogs',
  'operations.pageVisits',
  'operations.refreshTokenSessions',
  'commons.backlog',
  'commons.boardsAndCanvases',
  'commons.caseProvenance',
  'reciprocity.forwardPrompts',
  'commons.issuesSignalsStories',
  'modalities.coaching',
  'modalities.contribution',
  'modalities.mentoring',
  'modalities.peerSupport',
  'modalities.training',
  'modalities.volunteering',
  'projects.initiatives',
  'feedback.submissions',
  'community.ideas',
] as const;

export type GdprUserDataInventoryItem = (typeof GDPR_USER_DATA_INVENTORY)[number];

function anonymizedEmailFor(userId: string): string {
  return `deleted-${userId}@changemappers.deleted`;
}

type GdprDelegateMethod = (args: Record<string, unknown>) => Prisma.PrismaPromise<unknown>;
type GdprDelegate = Partial<Record<'findMany' | 'findUnique' | 'deleteMany' | 'updateMany', GdprDelegateMethod>>;

function getDelegate(client: GdprPrismaClient, model: string): GdprDelegate {
  return (client as unknown as Record<string, GdprDelegate>)[model] ?? {};
}

function callDelegate(
  client: GdprPrismaClient,
  model: string,
  method: 'findMany' | 'findUnique' | 'deleteMany' | 'updateMany',
  args: Record<string, unknown>,
): Prisma.PrismaPromise<unknown> {
  const delegate = getDelegate(client, model);
  const fn = delegate[method];
  if (!fn) throw new Error(`GDPR delegate missing: ${model}.${method}`);
  return fn(args);
}

function findMany(client: GdprPrismaClient, model: string, where: Record<string, unknown>) {
  return callDelegate(client, model, 'findMany', { where });
}

function deleteMany(client: GdprPrismaClient, model: string, where: Record<string, unknown>) {
  return callDelegate(client, model, 'deleteMany', { where });
}

function updateMany(client: GdprPrismaClient, model: string, where: Record<string, unknown>, data: Record<string, unknown>) {
  return callDelegate(client, model, 'updateMany', { where, data });
}

function buildExtendedUserErasureOperations(client: GdprPrismaClient, userId: string, erasedAt: Date): Prisma.PrismaPromise<unknown>[] {
  return [
    deleteMany(client, 'backlogResonance', { userId }),
    updateMany(client, 'backlogItem', { createdById: userId }, { title: 'Deleted backlog item', description: '[deleted]' }),
    updateMany(client, 'board', { ownerId: userId }, { ownerId: null, deletedAt: erasedAt }),
    updateMany(client, 'canvasNodeComment', { authorId: userId }, { content: '[deleted]', deletedAt: erasedAt }),
    updateMany(client, 'coachingOffer', { coachId: userId }, { coacheeKnow: '[deleted]', isArchived: true }),
    updateMany(client, 'coachingRequest', { requesterId: userId }, { stuckOn: '[deleted]', shiftsWanted: '[deleted]', isWithdrawn: true }),
    updateMany(client, 'contributionOffer', { offererId: userId }, { prerequisites: null, isArchived: true }),
    updateMany(client, 'contributionRequest', { requesterId: userId }, { whatNeeded: '[deleted]', alreadyTried: null, willDoWith: null, isWithdrawn: true }),
    updateMany(client, 'mentorProfile', { userId }, { whatCanOffer: '[deleted]', professionalUrl: null, isArchived: true }),
    updateMany(client, 'mentoringRequest', { requesterId: userId }, { inflectionPoint: '[deleted]', guidanceSought: '[deleted]', isWithdrawn: true }),
    updateMany(client, 'peerSupportOffer', { offererId: userId }, { boundaryStatement: '[deleted]', isArchived: true, isPaused: true }),
    updateMany(client, 'peerSupportRequest', { requesterId: userId }, { whatSupportLooks: '[deleted]', whatNotLooking: '[deleted]', isWithdrawn: true }),
    updateMany(client, 'trainingOffer', { creatorId: userId }, { description: '[deleted]', professionalUrl: null, isArchived: true, city: null, cityLat: null, cityLng: null }),
    updateMany(client, 'trainingRequest', { requesterId: userId }, { skillGapDescription: '[deleted]', isWithdrawn: true }),
    updateMany(client, 'feedback', { userId }, { userId: null, expectation: '[deleted]', reality: '[deleted]', improvement: null, otherComment: null, metadata: {} }),
    updateMany(client, 'event', { hostId: userId }, { deletedAt: erasedAt, description: null, address: null, onlineLink: null, facebookEventUrl: null, latitude: null, longitude: null }),
    deleteMany(client, 'eventOrganizer', { userId }),
    updateMany(client, 'caseWithProvenance', { authorId: userId }, { contributorNotes: null, attribution: 'Deleted user', lineageAcknowledgment: null }),
    deleteMany(client, 'forwardReciprocityPrompt', { userId }),
    updateMany(client, 'user', { invitedById: userId }, { invitedById: null }),
    updateMany(client, 'compassProfile', { userId }, { northStar: null, originQuestion: null, biographyEntries: {}, communicationNote: null, conflictStyleNote: null, emotionalPattern: null, energyPatterns: null, experiments: {}, riskFears: null, storyShift: null, storyVision: null, storyWhy: null, supportNetwork: {}, translationMap: {} }),
    updateMany(client, 'energyCanvas', { createdById: userId }, { description: null, stateReason: null, deletedAt: erasedAt }),
    updateMany(client, 'energyEntity', { createdById: userId }, { roleLabel: 'Deleted entity', notes: null, widgetContent: null, deletedAt: erasedAt }),
    updateMany(client, 'energyRelation', { createdById: userId }, { notes: null, patternDetected: null, deletedAt: erasedAt }),
    updateMany(client, 'energyPatternEntry', { proposedById: userId }, { definition: '[deleted]', mechanismDescription: '[deleted]', realWorldExamples: '[deleted]', status: 'RETIRED' }),
    updateMany(client, 'patternLibraryEntry', { proposedById: userId }, { requirements: null, limitations: null, examples: null, status: 'RETIRED' }),
    updateMany(client, 'initiative', { createdById: userId }, { description: '[deleted]', why: '[deleted]', archivedAt: erasedAt, archiveReason: 'Author erased' }),
    updateMany(client, 'initiative', { assigneeId: userId }, { assigneeId: null }),
    deleteMany(client, 'initiativeRole', { userId }),
    updateMany(client, 'initiativeUpdate', { authorId: userId }, { narrative: '[deleted]', whatShifting: null, whatHard: null, helpNeeded: null }),
    updateMany(client, 'interventionRecord', { authorId: userId }, { reflection: '[deleted]' }),
    // 2026-06-18 audit G2 (Art. 17): MentoringFeedback.authorId and
    // PeerSupportFeedback.authorId are bare String fields with no @relation to
    // User, so deleting a user never cascades to them. Scrub their free-text PII
    // by authorId, mirroring interventionRecord. The bare-authorId guard in
    // gdpr-user-data.test.ts asserts every such model is covered here.
    updateMany(client, 'mentoringFeedback', { authorId: userId }, { reflection: '[deleted]' }),
    updateMany(client, 'peerSupportFeedback', { authorId: userId }, { publicNote: null }),
    deleteMany(client, 'issueDispute', { userId }),
    deleteMany(client, 'issueVouch', { userId }),
    deleteMany(client, 'appreciate', { OR: [{ giverId: userId }, { targetUserId: userId }] }),
    updateMany(client, 'story', { authorId: userId }, { title: 'Deleted story', summary: '[deleted]', context: '[deleted]', challenge: '[deleted]', whatHappened: '[deleted]', outcome: '[deleted]', lessonsLearned: '[deleted]', retrospectiveWhatWorked: null, retrospectiveWhatToChange: null, retrospectiveAdvice: null }),
    updateMany(client, 'storyComment', { authorId: userId }, { content: '[deleted]' }),
    updateMany(client, 'socialIssue', { createdById: userId }, { description: null, sources: [], locationName: null, deletedAt: erasedAt }),
    updateMany(client, 'weakSignal', { createdById: userId }, { description: '[deleted]', context: null, sourceUrl: null, locationName: null, deletedAt: erasedAt }),
    deleteMany(client, 'signalResonanceVote', { userId }),
    updateMany(client, 'signalCorroboration', { userId }, { evidence: '[deleted]', sourceUrl: null }),
    updateMany(client, 'weakSignalPattern', { proposedById: userId }, { description: '[deleted]', hypothesis: null, status: 'RETIRED' }),
    updateMany(client, 'signalCollection', { createdById: userId }, { description: null }),
    deleteMany(client, 'signalCollectionItem', { addedById: userId }),
    updateMany(client, 'signalProjectLink', { linkedById: userId }, { note: null }),
    updateMany(client, 'signalCommunityLink', { linkedById: userId }, { note: null }),
    updateMany(client, 'systemsCanvas', { createdById: userId }, { description: null, diagramXml: null, status: 'ARCHIVED' }),
    updateMany(client, 'systemsCanvasNode', { createdById: userId }, { title: 'Deleted node', description: null, deletedAt: erasedAt }),
    deleteMany(client, 'projectReflection', { userId }),
    deleteMany(client, 'reflectionRecord', { userId }),
    deleteMany(client, 'rootCauseDiagnostic', { authorId: userId }),
    deleteMany(client, 'savedVolunteerOpportunity', { userId }),
    updateMany(client, 'volunteerApplication', { volunteerId: userId }, { message: null, availabilityDetails: null, relevantExperience: null, volunteerFeedback: null, requesterFeedback: null, cancelledAt: erasedAt }),
    updateMany(client, 'volunteerOpportunity', { requesterId: userId }, { description: null, location: null, latitude: null, longitude: null, equipmentNeeded: null, dressCode: null, expectedImpact: null, impactMeasurement: null, moreInfoUrl: null, deletedAt: erasedAt }),
    deleteMany(client, 'announcementAck', { userId }),
    deleteMany(client, 'communityMember', { userId }),
    deleteMany(client, 'eventRsvp', { userId }),
    deleteMany(client, 'userOnboardingJourneyStep', { userId }),
    // Community ideas: votes deleted (like BacklogResonance); idea posts + comments scrub-retained
    // in place for community continuity (like Story/Initiative/StoryComment). User row is anonymized,
    // not deleted, so the Restrict FKs on createdById/userId hold.
    deleteMany(client, 'ideaVote', { userId }),
    updateMany(client, 'ideaComment', { userId }, { content: '[deleted]' }),
    updateMany(client, 'ideaPost', { createdById: userId }, { title: 'Deleted idea', description: '[deleted]', tags: [], rdgTags: [] }),
  ];
}

async function buildExtendedGdprExportDomains(client: GdprPrismaClient, userId: string) {
  const [
    backlogItems,
    backlogResonances,
    boards,
    canvasNodeComments,
    coachingOffers,
    coachingRequests,
    contributionOffers,
    contributionRequests,
    mentorProfiles,
    mentoringRequests,
    peerSupportOffers,
    peerSupportRequests,
    trainingOffers,
    trainingRequests,
    feedback,
    compassProfiles,
    eventOrganizerRoles,
    caseProvenance,
    forwardPrompts,
    energyCanvases,
    energyEntities,
    energyRelations,
    energyPatternEntries,
    patternLibraryEntries,
    hostedEvents,
    initiativesCreated,
    initiativesAssigned,
    initiativeRoles,
    initiativeUpdates,
    interventionRecords,
    issueDisputes,
    issueVouches,
    appreciationsGiven,
    appreciationsReceived,
    stories,
    storyComments,
    socialIssues,
    weakSignals,
    signalResonanceVotes,
    signalCorroborations,
    weakSignalPatterns,
    signalCollections,
    signalCollectionItems,
    signalProjectLinks,
    signalCommunityLinks,
    systemsCanvases,
    systemsCanvasNodes,
    projectReflections,
    reflectionRecords,
    rootCauseDiagnostics,
    savedVolunteerOpportunities,
    volunteerApplications,
    volunteerOpportunities,
    announcementAcks,
    ideaPosts,
    ideaVotes,
    ideaComments,
  ] = await Promise.all([
    findMany(client, 'backlogItem', { createdById: userId }),
    findMany(client, 'backlogResonance', { userId }),
    findMany(client, 'board', { ownerId: userId }),
    findMany(client, 'canvasNodeComment', { authorId: userId }),
    findMany(client, 'coachingOffer', { coachId: userId }),
    findMany(client, 'coachingRequest', { requesterId: userId }),
    findMany(client, 'contributionOffer', { offererId: userId }),
    findMany(client, 'contributionRequest', { requesterId: userId }),
    findMany(client, 'mentorProfile', { userId }),
    findMany(client, 'mentoringRequest', { requesterId: userId }),
    findMany(client, 'peerSupportOffer', { offererId: userId }),
    findMany(client, 'peerSupportRequest', { requesterId: userId }),
    findMany(client, 'trainingOffer', { creatorId: userId }),
    findMany(client, 'trainingRequest', { requesterId: userId }),
    findMany(client, 'feedback', { userId }),
    findMany(client, 'compassProfile', { userId }),
    findMany(client, 'eventOrganizer', { userId }),
    findMany(client, 'caseWithProvenance', { authorId: userId }),
    findMany(client, 'forwardReciprocityPrompt', { userId }),
    findMany(client, 'energyCanvas', { createdById: userId }),
    findMany(client, 'energyEntity', { createdById: userId }),
    findMany(client, 'energyRelation', { createdById: userId }),
    findMany(client, 'energyPatternEntry', { proposedById: userId }),
    findMany(client, 'patternLibraryEntry', { proposedById: userId }),
    findMany(client, 'event', { hostId: userId }),
    findMany(client, 'initiative', { createdById: userId }),
    findMany(client, 'initiative', { assigneeId: userId }),
    findMany(client, 'initiativeRole', { userId }),
    findMany(client, 'initiativeUpdate', { authorId: userId }),
    findMany(client, 'interventionRecord', { authorId: userId }),
    findMany(client, 'issueDispute', { userId }),
    findMany(client, 'issueVouch', { userId }),
    findMany(client, 'appreciate', { giverId: userId }),
    findMany(client, 'appreciate', { targetUserId: userId }),
    findMany(client, 'story', { authorId: userId }),
    findMany(client, 'storyComment', { authorId: userId }),
    findMany(client, 'socialIssue', { createdById: userId }),
    findMany(client, 'weakSignal', { createdById: userId }),
    findMany(client, 'signalResonanceVote', { userId }),
    findMany(client, 'signalCorroboration', { userId }),
    findMany(client, 'weakSignalPattern', { proposedById: userId }),
    findMany(client, 'signalCollection', { createdById: userId }),
    findMany(client, 'signalCollectionItem', { addedById: userId }),
    findMany(client, 'signalProjectLink', { linkedById: userId }),
    findMany(client, 'signalCommunityLink', { linkedById: userId }),
    findMany(client, 'systemsCanvas', { createdById: userId }),
    findMany(client, 'systemsCanvasNode', { createdById: userId }),
    findMany(client, 'projectReflection', { userId }),
    findMany(client, 'reflectionRecord', { userId }),
    findMany(client, 'rootCauseDiagnostic', { authorId: userId }),
    findMany(client, 'savedVolunteerOpportunity', { userId }),
    findMany(client, 'volunteerApplication', { volunteerId: userId }),
    findMany(client, 'volunteerOpportunity', { requesterId: userId }),
    findMany(client, 'announcementAck', { userId }),
    findMany(client, 'ideaPost', { createdById: userId }),
    findMany(client, 'ideaVote', { userId }),
    findMany(client, 'ideaComment', { userId }),
  ]);

  return {
    commons: {
      backlog: { items: backlogItems, resonances: backlogResonances },
      boardsAndCanvases: { boards, canvasNodeComments, systemsCanvases, systemsCanvasNodes, energyCanvases, energyEntities, energyRelations, energyPatternEntries, patternLibraryEntries, compassProfiles },
      caseProvenance,
      issuesSignalsStories: {
        socialIssues,
        issueDisputes,
        issueVouches,
        weakSignals,
        signalResonanceVotes,
        signalCorroborations,
        weakSignalPatterns,
        signalCollections,
        signalCollectionItems,
        signalProjectLinks,
        signalCommunityLinks,
        stories,
        storyComments,
        appreciationsGiven,
        appreciationsReceived,
      },
    },
    modalities: {
      coaching: { offers: coachingOffers, requests: coachingRequests },
      contribution: { offers: contributionOffers, requests: contributionRequests },
      mentoring: { profiles: mentorProfiles, requests: mentoringRequests },
      peerSupport: { offers: peerSupportOffers, requests: peerSupportRequests },
      training: { offers: trainingOffers, requests: trainingRequests },
      volunteering: { saved: savedVolunteerOpportunities, applications: volunteerApplications, opportunities: volunteerOpportunities },
    },
    projects: { initiativesCreated, initiativesAssigned, initiativeRoles, initiativeUpdates, interventionRecords, projectReflections, reflectionRecords, rootCauseDiagnostics },
    feedback: { submissions: feedback },
    events: { hosted: hostedEvents, organizerRoles: eventOrganizerRoles },
    announcementAcks,
    reciprocity: { forwardPrompts },
    community: { ideas: { posts: ideaPosts, votes: ideaVotes, comments: ideaComments } },
  };
}

export function buildUserErasureOperations(client: GdprPrismaClient, userId: string, erasedAt: Date = new Date()) {
  return [
    client.user.update({
      where: { id: userId },
      data: {
        deletedAt: erasedAt,
        scheduledDeletionAt: null,
        scheduledDeletionReason: null,
        inactiveAt: null,
        inactivityWarning30SentAt: null,
        inactivityWarning15SentAt: null,
        inactivityWarning3SentAt: null,
        inactivityFinalNoticeSentAt: null,
        processingRestricted: true,
        declineAlgorithmicMatching: true,
        showOnMap: false,
        profileVisibility: Visibility.CONNECTIONS,
        locationVisibility: Visibility.CONNECTIONS,
        name: 'Törölt felhasználó',
        displayName: 'Törölt felhasználó',
        email: anonymizedEmailFor(userId),
        passwordHash: '',
        invitedById: null,
        bio: null,
        motto: null,
        profilePhoto: null,
        coverImage: null,
        website: null,
        socialLinks: {},
        city: null,
        country: null,
        region: null,
        latitude: null,
        longitude: null,
        enjoyDoing: null,
        currentIntention: null,
        constraints: null,
        availabilityDetails: {},
        collaborationPreference: [],
        verificationToken: null,
        verificationTokenExpiry: null,
        invitationCode: null,
        didPublicKey: null,
        federationConsentAt: null,
        federationSettings: {},
        usedInviteCode: null,
        lastInviteSlotGranted: null,
        lastUnreadNotificationAt: null,
        lastReflectionReminderAt: null,
        reflectionReminderOptOut: false,
        featureVisibilityPreferences: Prisma.JsonNull,
        mainCommunity: null,
        rdgAreas: [],
        mainCauses: { set: [] },
        interestedCauses: { set: [] },
        managedCauses: { set: [] },
      },
    }),
    client.userSkill.deleteMany({ where: { userId } }),
    client.userValue.deleteMany({ where: { userId } }),
    client.userInterest.deleteMany({ where: { userId } }),
    client.userFunctionalProfile.deleteMany({ where: { userId } }),
    client.userOnboardingState.deleteMany({ where: { userId } }),
    client.refreshTokenSession.deleteMany({ where: { userId } }),
    client.twoFactorBackupCode.deleteMany({ where: { userId } }),
    client.pageVisitLog.deleteMany({ where: { userId } }),
    client.matchRejectionLog.deleteMany({ where: { OR: [{ targetUserId: userId }, { candidateUserId: userId }] } }),
    client.message.deleteMany({ where: { OR: [{ senderId: userId }, { receiverId: userId }] } }),
    client.notification.deleteMany({ where: { userId } }),
    client.notification.updateMany({ where: { senderId: userId }, data: { senderId: null } }),
    client.connection.deleteMany({ where: { OR: [{ senderId: userId }, { receiverId: userId }] } }),
    client.feedCommentReaction.deleteMany({ where: { userId } }),
    client.feedPostReaction.deleteMany({ where: { userId } }),
    client.feedPostRdgAnnotation.deleteMany({ where: { userId } }),
    client.feedPostTagAnnotation.deleteMany({ where: { userId } }),
    client.feedMention.deleteMany({ where: { mentionedUserId: userId } }),
    client.feedComment.updateMany({
      where: { authorId: userId },
      data: { content: '[deleted]', plainText: null, deletedAt: erasedAt },
    }),
    client.feedPost.updateMany({
      where: { authorId: userId },
      data: { content: null, plainText: null, attachments: {}, youtubeLinks: [], deletedAt: erasedAt },
    }),
    client.pitchEndorsement.deleteMany({ where: { endorserId: userId } }),
    client.pitch.updateMany({
      where: { authorId: userId },
      data: { contactEmail: null, usePlatformMessaging: false, archivedAt: erasedAt },
    }),
    client.coachMeSession.deleteMany({ where: { userId } }),
    client.coachMeConsent.deleteMany({ where: { userId } }),
    client.invite.deleteMany({ where: { createdById: userId } }),
    client.invite.updateMany({ where: { recipientId: userId }, data: { recipientId: null, recipientEmail: null } }),
    client.invite.updateMany({ where: { revokedById: userId }, data: { revokedById: null, revokeReason: null } }),
    client.schedulingPoll.updateMany({
      where: { creatorId: userId },
      data: {
        creatorId: null,
        // Random UUIDs ensure the erased token does not contain or leak the userId.
        participantToken: randomUUID(),
        organizerToken: randomUUID(),
        organizerName: 'Törölt felhasználó',
      },
    }),
    client.schedulingResponse.updateMany({
      where: { userId },
      data: { participantName: 'Deleted user', userId: null },
    }),
    client.report.updateMany({ where: { filerId: userId }, data: { description: null } }),
    client.report.updateMany({ where: { targetId: userId }, data: { description: null } }),
    client.auditLog.updateMany({ where: { userId }, data: { userId: null, userEmail: null, ipAddress: null, userAgent: null } }),
    ...buildExtendedUserErasureOperations(client, userId, erasedAt),
  ];
}

export async function eraseUserPersonalData(client: GdprPrismaClient, userId: string, erasedAt: Date = new Date()): Promise<void> {
  await client.$transaction(buildUserErasureOperations(client, userId, erasedAt));
}

export async function buildGdprExportPayload(userId: string, client: GdprPrismaClient = prisma) {
  const [
    user,
    functionalProfile,
    onboardingState,
    skills,
    values,
    interests,
    sentMessages,
    receivedMessages,
    notifications,
    sentNotifications,
    createdInvites,
    receivedInvites,
    revokedInvites,
    sentConnections,
    receivedConnections,
    feedPosts,
    feedComments,
    feedPostReactions,
    feedCommentReactions,
    feedRdgAnnotations,
    feedTagAnnotations,
    feedMentions,
    pitches,
    pitchEndorsements,
    coachMeConsent,
    coachMeSessions,
    memberships,
    eventRsvps,
    schedulingPolls,
    schedulingResponses,
    reportsFiled,
    reportsTargetingUser,
    auditLogs,
    pageVisits,
    refreshTokenSessions,
  ] = await Promise.all([
    client.user.findUnique({
      where: { id: userId },
      select: {
        id: true,
        name: true,
        invitedById: true,
        email: true,
        displayName: true,
        bio: true,
        motto: true,
        website: true,
        socialLinks: true,
        federationSettings: true,
        federationConsentAt: true,
        profileVisibility: true,
        locationVisibility: true,
        locationPrecision: true,
        showOnMap: true,
        processingRestricted: true,
        declineAlgorithmicMatching: true,
        reflectionReminderOptOut: true,
        featureVisibilityPreferences: true,
        city: true,
        region: true,
        country: true,
        latitude: true,
        longitude: true,
        createdAt: true,
        updatedAt: true,
        lastActiveAt: true,
        lastLoginAt: true,
        archetypes: true,
        changemakeLevel: true,
        profileType: true,
        seekingLocalEcoCommunity: true,
        seekingIntentionalCommunity: true,
        highStakesProjectHelp: true,
        strictNoRomance: true,
        mainCauses: { select: { id: true, title: true } },
        interestedCauses: { select: { id: true, title: true } },
        managedCauses: { select: { id: true, title: true } },
        claimedCommunities: { select: { id: true, name: true } },
        ownedCommunities: { select: { id: true, name: true } },
        claimedEvents: { select: { id: true, title: true, status: true } },
      },
    }),
    client.userFunctionalProfile.findUnique({
      where: { userId },
      select: {
        cmapLevel: true,
        assessmentResponses: true,
        networkRoles: true,
        availabilityMode: true,
        currentOffer: true,
        focusMode: true,
        rdgMain: true,
        rdgInterested: true,
        currentProjectDescription: true,
        momentNeeds: true,
        protectionNeeds: true,
        developmentGaps: true,
        systemicExperience: true,
        updatedAt: true,
      },
    }),
    client.userOnboardingState.findUnique({
      where: { userId },
      select: {
        lastStageCompleted: true,
        agreementsAcceptedAt: true,
        orientationSeenAt: true,
        updatedAt: true,
      },
    }),
    client.userSkill.findMany({ where: { userId }, select: { skill: true, skillType: true } }),
    client.userValue.findMany({ where: { userId }, select: { value: true } }),
    client.userInterest.findMany({ where: { userId }, select: { interest: true } }),
    client.message.findMany({ where: { senderId: userId }, select: { id: true, receiverId: true, content: true, isRead: true, createdAt: true, editedAt: true, deletedAt: true } }),
    client.message.findMany({ where: { receiverId: userId }, select: { id: true, senderId: true, content: true, isRead: true, createdAt: true, editedAt: true, deletedAt: true } }),
    client.notification.findMany({ where: { userId }, select: { id: true, type: true, title: true, message: true, link: true, isRead: true, senderId: true, eventId: true, communityId: true, createdAt: true } }),
    client.notification.findMany({ where: { senderId: userId }, select: { id: true, userId: true, type: true, title: true, message: true, link: true, isRead: true, eventId: true, communityId: true, createdAt: true } }),
    client.invite.findMany({ where: { createdById: userId }, select: { id: true, code: true, recipientEmail: true, recipientId: true, status: true, resendCount: true, createdAt: true, sentAt: true, openedAt: true, acceptedAt: true, expiresAt: true, revokedAt: true, revokedById: true, revokeReason: true, notes: true } }),
    client.invite.findMany({ where: { recipientId: userId }, select: { id: true, code: true, createdById: true, recipientEmail: true, status: true, createdAt: true, sentAt: true, openedAt: true, acceptedAt: true, expiresAt: true } }),
    client.invite.findMany({ where: { revokedById: userId }, select: { id: true, code: true, createdById: true, recipientEmail: true, recipientId: true, status: true, revokedAt: true, revokeReason: true } }),
    client.connection.findMany({ where: { senderId: userId }, select: { id: true, receiverId: true, type: true, status: true, message: true, createdAt: true, updatedAt: true, respondedAt: true, deletedAt: true } }),
    client.connection.findMany({ where: { receiverId: userId }, select: { id: true, senderId: true, type: true, status: true, message: true, createdAt: true, updatedAt: true, respondedAt: true, deletedAt: true } }),
    client.feedPost.findMany({ where: { authorId: userId }, select: { id: true, content: true, plainText: true, attachments: true, youtubeLinks: true, visibility: true, status: true, createdAt: true, updatedAt: true, deletedAt: true, communityId: true } }),
    client.feedComment.findMany({ where: { authorId: userId }, select: { id: true, postId: true, parentId: true, content: true, plainText: true, createdAt: true, updatedAt: true, deletedAt: true } }),
    client.feedPostReaction.findMany({ where: { userId }, select: { id: true, postId: true, type: true, createdAt: true } }),
    client.feedCommentReaction.findMany({ where: { userId }, select: { id: true, commentId: true, type: true, createdAt: true } }),
    client.feedPostRdgAnnotation.findMany({ where: { userId }, select: { id: true, postId: true, source: true, rdgSlug: true, createdAt: true, updatedAt: true } }),
    client.feedPostTagAnnotation.findMany({ where: { userId }, select: { id: true, postId: true, source: true, tagKey: true, tagLabel: true, tagCategory: true, createdAt: true, updatedAt: true } }),
    client.feedMention.findMany({ where: { mentionedUserId: userId }, select: { id: true, postId: true, commentId: true, createdAt: true } }),
    client.pitch.findMany({
      where: { authorId: userId },
      select: { id: true, name: true, summary: true, location: true, website: true, language: true, localContext: true, systemicChallenge: true, vision: true, expectedOutcomes: true, teamDescription: true, experience: true, evidenceLinks: true, stage: true, mainObstacles: true, needsSkills: true, needsFunding: true, fundingAmount: true, fundingCurrency: true, needsPartners: true, needsVolunteers: true, needsKnowledge: true, needsOther: true, callToAction: true, contactEmail: true, usePlatformMessaging: true, status: true, publishedAt: true, topicTags: true, communityId: true, initiativeId: true, createdAt: true, updatedAt: true, archivedAt: true },
    }),
    client.pitchEndorsement.findMany({ where: { endorserId: userId }, select: { id: true, pitchId: true, message: true, createdAt: true } }),
    client.coachMeConsent.findUnique({ where: { userId }, select: { id: true, agreedAt: true, encryptionModel: true, encryptionSalt: true, encryptedDek: true } }),
    client.coachMeSession.findMany({ where: { userId }, select: { id: true, focusTag: true, customFocusTag: true, whyImportant: true, sessionGoal: true, miracleSignsA: true, miracleSignsB: true, miracleSignsC: true, miracleOptional: true, actionPlanV1: true, actionPlanFinal: true, actionOptional: true, sessionUsefulness: true, finalReflections: true, currentPhase: true, createdAt: true, updatedAt: true, completedAt: true, archivedAt: true } }),
    client.communityMember.findMany({ where: { userId }, select: { id: true, role: true, status: true, joinedAt: true, community: { select: { id: true, name: true } } } }),
    client.eventRsvp.findMany({ where: { userId }, select: { id: true, status: true, createdAt: true, updatedAt: true, event: { select: { id: true, title: true } } } }),
    client.schedulingPoll.findMany({ where: { creatorId: userId }, select: { id: true, participantToken: true, organizerToken: true, title: true, description: true, organizerName: true, location: true, timezone: true, confirmedAt: true, isArchived: true, createdAt: true, updatedAt: true, expiresAt: true } }),
    client.schedulingResponse.findMany({ where: { userId }, select: { id: true, pollId: true, participantName: true, participantToken: true, createdAt: true, updatedAt: true, votes: { select: { timeOptionId: true, vote: true } } } }),
    client.report.findMany({ where: { filerId: userId }, select: { id: true, targetId: true, targetType: true, category: true, description: true, status: true, resolution: true, resolvedAt: true, resolvedById: true, createdAt: true } }),
    client.report.findMany({ where: { targetId: userId }, select: { id: true, filerId: true, targetType: true, category: true, description: true, status: true, resolution: true, resolvedAt: true, resolvedById: true, createdAt: true } }),
    client.auditLog.findMany({ where: { userId }, select: { action: true, entityType: true, entityId: true, metadata: true, createdAt: true } }),
    client.pageVisitLog.findMany({ where: { userId }, select: { path: true, module: true, userArchetypes: true, createdAt: true } }),
    client.refreshTokenSession.findMany({ where: { userId }, select: { id: true, familyId: true, expiresAt: true, consumedAt: true, revokedAt: true, createdAt: true } }),
  ]);

  if (!user) return null;

  const extendedDomains = await buildExtendedGdprExportDomains(client, userId);

  const decryptedSentMessages = decryptDirectMessageRows(sentMessages);
  const decryptedReceivedMessages = decryptDirectMessageRows(receivedMessages);
  return {
    generatedAt: new Date().toISOString(),
    inventoryVersion: '2026-05-06',
    inventory: GDPR_USER_DATA_INVENTORY,
    account: { ...user, functionalProfile, onboardingState, skills, values, interests },
    communications: {
      directMessages: { sent: decryptedSentMessages, received: decryptedReceivedMessages },
      notifications: { received: notifications, sent: sentNotifications },
      invitations: { created: createdInvites, received: receivedInvites, revoked: revokedInvites },
    },
    social: {
      connections: { sent: sentConnections, received: receivedConnections },
      feed: { posts: feedPosts, comments: feedComments, reactions: { posts: feedPostReactions, comments: feedCommentReactions }, annotations: { rdgs: feedRdgAnnotations, tags: feedTagAnnotations }, mentions: feedMentions },
    },
    projects: { pitches, pitchEndorsements, ...extendedDomains.projects },
    support: { coachMeConsent, coachMeSessions },
    memberships,
    events: { rsvps: eventRsvps, hosted: extendedDomains.events.hosted, organizerRoles: extendedDomains.events.organizerRoles },
    scheduling: { polls: schedulingPolls, responses: schedulingResponses },
    trust: { reportsFiled, reportsTargetingUser },
    operations: { auditLogs, pageVisits, refreshTokenSessions },
    commons: extendedDomains.commons,
    modalities: extendedDomains.modalities,
    feedback: extendedDomains.feedback,
    announcementAcks: extendedDomains.announcementAcks,
    reciprocity: extendedDomains.reciprocity,
    community: extendedDomains.community,
  };
}
