// Curated batch demo user specs for the admin demo seeding tools.
import { Archetype, ChangemakerLevel, SkillType } from "@/lib/prisma";
import { normalizeRdgId } from '@/lib/taxonomy';

export const DEMO_RDG_AREA_ALIASES: Record<string, string> = {
  "élelmiszer-szuverenitás": "RDG12",
  "tájrehabilitáció": "RDG07",
  "permakultúra": "RDG12",
  "közösségi reziliencia": "RDG20",
  "demokratikus részvétel": "RDG19",
  "oktatási hozzáférés": "RDG03",
  "intézményi átalakulás": "RDG19",
  "körgazdaság": "RDG15",
  "klímapolitika": "RDG10",
  "klímaigazságosság": "RDG21",
  "energiaátmenet": "RDG16",
  "globális aktivizmus": "RDG29",
  "méltányos gazdaság": "RDG14",
  "hulladékcsökkentés": "RDG15",
  "regeneratív vállalkozás": "RDG13",
  "energiaközösségek": "RDG16",
  "decentralizált energia": "RDG16",
  "technológiai etika": "RDG28",
  "klímaadaptáció": "RDG10",
  "mezőgazdasági rendszerek": "RDG12",
  "vízgazdálkodás": "RDG08",
  "impakt vállalkozások": "RDG13",
  "helyi gazdaságfejlesztés": "RDG14",
  "kooperatív modellek": "RDG14",
  "ökológiai oktatás": "RDG03",
  "közösségi tanulás": "RDG20",
  "természetkapcsolat": "RDG09",
  "regeneratív mezőgazdaság": "RDG12",
  "biodiverzitás": "RDG09",
};

export function normalizeDemoRdgAreas(values: string[]): string[] {
  return Array.from(new Set(values.map((value) => normalizeRdgId(value) ?? DEMO_RDG_AREA_ALIASES[value.toLowerCase()] ?? value)));
}

export interface BatchUserSpec {
  name: string;
  displayName: string;
  pronouns: string;
  emailSlug: string;
  bio: string;
  motto: string;
  website: string;
  city: string;
  region: string;
  latitude: number;
  longitude: number;
  archetypes: Archetype[];
  changemakeLevel: ChangemakerLevel;
  organizationName: string;
  workingSectors: string[];
  collaborationPreference: string[];
  rdgAreas: string[];
  enjoyDoing: string;
  currentIntention: string;
  primaryLanguage: string;
  spokenLanguages: string[];
  availability: "AVAILABLE" | "BUSY" | "AWAY";
  seekingConnections: boolean;
  seekingCoFounders: boolean;
  seekingSupport: boolean;
  skills: { skill: string; skillType: SkillType }[];
  values: string[];
  interests: string[];
}

export const BATCH_DEMO_USERS: BatchUserSpec[] = [
  {
    name: "Fekete Anna",
    displayName: "Anna",
    pronouns: "ő/övé",
    emailSlug: "fekete.anna",
    bio: "Permakultúra-oktató és közösségi kertész, aki tíz éve segít városiaknak visszakapcsolódni a természethez. Saját permakertet vezet Budapest határán, és havi workshopokat tart kezdőknek és haladóknak egyaránt.",
    motto: "A föld nem az örökségünk — a gyermekeinktől kaptuk kölcsön.",
    website: "https://feketeanna-permakert.hu",
    city: "Budapest",
    region: "Budapest",
    latitude: 47.4979,
    longitude: 19.0402,
    archetypes: [Archetype.LOCAL_PRACTITIONER, Archetype.MYCELIUM],
    changemakeLevel: ChangemakerLevel.LEVEL_5,
    organizationName: "Gyökér Permakultúra Műhely",
    workingSectors: ["oktatás", "élelmiszer-szuverenitás", "közösségépítés"],
    collaborationPreference: [
      "helyi projektek",
      "workshop-szervezés",
      "mentorálás",
    ],
    rdgAreas: [
      "élelmiszer-szuverenitás",
      "tájrehabilitáció",
      "ökológiai oktatás",
    ],
    enjoyDoing:
      "Kertészkedem, tanítok, és összekapcsolom az embereket a talajjal és egymással.",
    currentIntention:
      "Permakultúra-hálózatot szeretnék kiépíteni Budapest agglomerációjában.",
    primaryLanguage: "hu",
    spokenLanguages: ["hu", "en"],
    availability: "AVAILABLE",
    seekingConnections: true,
    seekingCoFounders: true,
    seekingSupport: false,
    skills: [
      { skill: "permakultúra-tervezés", skillType: SkillType.OFFERED },
      { skill: "workshop-facilitálás", skillType: SkillType.OFFERED },
      { skill: "közösségi kertészet", skillType: SkillType.OFFERED },
      { skill: "projektfinanszírozás", skillType: SkillType.SEEKING },
      { skill: "közösségszervezés", skillType: SkillType.EXPERIENCE },
    ],
    values: ["fenntarthatóság", "közösség", "természet", "tudásmegosztás"],
    interests: [
      "permakultúra",
      "élelmiszer-szuverenitás",
      "közösségi kertek",
      "ökológia",
    ],
  },
  {
    name: "Varga Márton",
    displayName: "Márton",
    pronouns: "ő/övé",
    emailSlug: "varga.marton",
    bio: "Közösségszervező és hálózatépítő, aki a pécsi civil szektort összekapcsolja a regionális és országos kezdeményezésekkel. Öt éve koordinálja a Dél-dunántúli Changemaker Hálózatot.",
    motto: "Egyedül gyorsabban jutunk el — de együtt messzebbre.",
    website: "https://vargamarton.com",
    city: "Pécs",
    region: "Baranya",
    latitude: 46.0727,
    longitude: 18.233,
    archetypes: [Archetype.NETWORK_WEAVER, Archetype.POLLINATOR],
    changemakeLevel: ChangemakerLevel.LEVEL_6,
    organizationName: "Dél-dunántúli Changemaker Hálózat",
    workingSectors: [
      "civil társadalom",
      "hálózatépítés",
      "regionális fejlesztés",
    ],
    collaborationPreference: [
      "hálózati együttműködések",
      "eseményszervezés",
      "mentorálás",
    ],
    rdgAreas: [
      "közösségi reziliencia",
      "demokratikus részvétel",
      "helyi gazdaság",
    ],
    enjoyDoing:
      "Embereket hozok össze, kapcsolatokat szövök, közös célokat találunk.",
    currentIntention:
      "Regionális changemaker találkozósorozatot indítok el 2026-ban.",
    primaryLanguage: "hu",
    spokenLanguages: ["hu", "en", "de"],
    availability: "AVAILABLE",
    seekingConnections: true,
    seekingCoFounders: false,
    seekingSupport: true,
    skills: [
      { skill: "hálózatépítés", skillType: SkillType.OFFERED },
      { skill: "facilitálás", skillType: SkillType.OFFERED },
      { skill: "eseményszervezés", skillType: SkillType.OFFERED },
      { skill: "kommunikáció", skillType: SkillType.OFFERED },
      { skill: "adatvizualizáció", skillType: SkillType.SEEKING },
    ],
    values: ["együttműködés", "bizalom", "sokszínűség", "helyi közösség"],
    interests: [
      "civil hálózatok",
      "részvételi demokrácia",
      "regionális fejlesztés",
      "storytelling",
    ],
  },
  {
    name: "Horváth Zsuzsanna",
    displayName: "Zsuzsa",
    pronouns: "ő/övé",
    emailSlug: "horvath.zsuzsanna",
    bio: "Fenntarthatósági stratéga és intézményi changemaker, aki nagyvállalatoktól önkormányzatokig segít szervezeteknek átállni a regeneratív működésre. Tíz éves tanácsadói tapasztalattal rendelkezik.",
    motto:
      "A rendszer belülről változik meg — ha a változtatók is belül vannak.",
    website: "https://zsuzsahorvath.eu",
    city: "Debrecen",
    region: "Hajdú-Bihar",
    latitude: 47.5316,
    longitude: 21.6244,
    archetypes: [Archetype.INSTITUTIONAL_CHANGEMAKER, Archetype.PRISM],
    changemakeLevel: ChangemakerLevel.LEVEL_7,
    organizationName: "Regeneratív Szervezetfejlesztés Kft.",
    workingSectors: [
      "szervezetfejlesztés",
      "önkormányzatok",
      "vállalati fenntarthatóság",
    ],
    collaborationPreference: [
      "stratégiai tanácsadás",
      "kutatás",
      "policy-alkotás",
    ],
    rdgAreas: ["intézményi átalakulás", "körgazdaság", "klímapolitika"],
    enjoyDoing: "Komplex rendszereket elemzek és segítek átalakulni belülről.",
    currentIntention:
      "Egy kelet-magyarországi önkormányzati fenntarthatósági programot indítok el.",
    primaryLanguage: "hu",
    spokenLanguages: ["hu", "en", "fr"],
    availability: "BUSY",
    seekingConnections: true,
    seekingCoFounders: false,
    seekingSupport: false,
    skills: [
      { skill: "szervezetfejlesztés", skillType: SkillType.OFFERED },
      { skill: "fenntarthatósági stratégia", skillType: SkillType.OFFERED },
      { skill: "rendszerszemléletű gondolkodás", skillType: SkillType.OFFERED },
      { skill: "policy-alkotás", skillType: SkillType.OFFERED },
      { skill: "körgazdasági tervezés", skillType: SkillType.EXPERIENCE },
    ],
    values: ["integritás", "rendszerszemlélet", "hosszú táv", "igazságosság"],
    interests: [
      "körgazdaság",
      "szervezeti kultúra",
      "közpolitika",
      "klímaadaptáció",
    ],
  },
  {
    name: "Kovács Tibor",
    displayName: "Tibor",
    pronouns: "ő/övé",
    emailSlug: "kovacs.tibor",
    bio: "Klímaaktivista és globális kampánykoordinátor, aki a helyi zöld mozgalmakat összeköti a nemzetközi hálózatokkal. Rendszeresen előad ENSZ klímakonferenciákon és európai fórumokon.",
    motto: "A helyi cselekvés a globális változás alapköve.",
    website: "https://tiborkovacs.org",
    city: "Győr",
    region: "Győr-Moson-Sopron",
    latitude: 47.6875,
    longitude: 17.6504,
    archetypes: [Archetype.GLOBAL_AMPLIFIER, Archetype.CANOPY],
    changemakeLevel: ChangemakerLevel.LEVEL_8,
    organizationName: "Klíma Jövő Alapítvány",
    workingSectors: ["klímavédelem", "advocacy", "médiakapcsolatok"],
    collaborationPreference: ["kampányok", "nemzetközi hálózatok", "média"],
    rdgAreas: ["klímaigazságosság", "energiaátmenet", "globális aktivizmus"],
    enjoyDoing:
      "Kampányokat vezetek, történeteket mesélek és mozgalmakat erősítek.",
    currentIntention:
      "Európai ifjúsági klímahálózatot akarok összekapcsolni a magyar mozgalommal.",
    primaryLanguage: "hu",
    spokenLanguages: ["hu", "en", "de", "es"],
    availability: "AVAILABLE",
    seekingConnections: true,
    seekingCoFounders: false,
    seekingSupport: true,
    skills: [
      { skill: "kampánymenedzsment", skillType: SkillType.OFFERED },
      { skill: "nyilvános kommunikáció", skillType: SkillType.OFFERED },
      { skill: "fundraising", skillType: SkillType.OFFERED },
      { skill: "médiakapcsolatok", skillType: SkillType.OFFERED },
      { skill: "adatelemzés", skillType: SkillType.SEEKING },
    ],
    values: [
      "klímaigazságosság",
      "bátorság",
      "szolidaritás",
      "globális felelősség",
    ],
    interests: [
      "klímamozgalom",
      "energiaátmenet",
      "ifjúsági szervezetek",
      "diplomácia",
    ],
  },
  {
    name: "Szabó Eszter",
    displayName: "Eszter",
    pronouns: "ő/övé",
    emailSlug: "szabo.eszter",
    bio: "Szociális vállalkozó és erőforrás-mobilizátor, aki marginalizált közösségek számára teremt gazdasági lehetőségeket. Miskolcon upcycling-manufaktúrát vezet, amely 30 embernek ad munkát.",
    motto: "Az erőforrások ott vannak, ahol odafigyelünk.",
    website: "https://ujraalkoto.hu",
    city: "Miskolc",
    region: "Borsod-Abaúj-Zemplén",
    latitude: 48.1035,
    longitude: 20.7784,
    archetypes: [Archetype.RESOURCE_MOBILIZER, Archetype.SPARK],
    changemakeLevel: ChangemakerLevel.LEVEL_6,
    organizationName: "Újraalkotó Szociális Manufaktúra",
    workingSectors: ["szociális vállalkozás", "körgazdaság", "foglalkoztatás"],
    collaborationPreference: [
      "projekttámogatás",
      "pénzügyi tanácsadás",
      "mentorálás",
    ],
    rdgAreas: [
      "méltányos gazdaság",
      "hulladékcsökkentés",
      "szociális innováció",
    ],
    enjoyDoing:
      "Rejtett lehetőségeket fedezek fel és embereket segítek kibontakozni.",
    currentIntention:
      "A manufaktúrát franchise-modellé szeretném fejleszteni más városok számára.",
    primaryLanguage: "hu",
    spokenLanguages: ["hu", "en"],
    availability: "AVAILABLE",
    seekingConnections: true,
    seekingCoFounders: true,
    seekingSupport: false,
    skills: [
      { skill: "szociális vállalkozás", skillType: SkillType.OFFERED },
      { skill: "pályázatírás", skillType: SkillType.OFFERED },
      { skill: "csapatvezetés", skillType: SkillType.OFFERED },
      { skill: "upcycling-design", skillType: SkillType.EXPERIENCE },
      { skill: "befektetői kapcsolatok", skillType: SkillType.SEEKING },
    ],
    values: ["méltányosság", "kreativitás", "közösség", "fenntarthatóság"],
    interests: [
      "szociális innováció",
      "körgazdaság",
      "foglalkoztatás",
      "design",
    ],
  },
  {
    name: "Nagy Bence",
    displayName: "Bence",
    pronouns: "ő/övé",
    emailSlug: "nagy.bence",
    bio: "Zöld technológiai vállalkozó és innovációs katalizátor, aki nyílt forráskódú energiaközösségi megoldásokat fejleszt kisvárosok számára. Startup-jával már hat helyi energiaközösséget indított el.",
    motto: "A legzöldebb energia az, amit közösen termelünk.",
    website: "https://opencommunityenergy.hu",
    city: "Székesfehérvár",
    region: "Fejér",
    latitude: 47.186,
    longitude: 18.4221,
    archetypes: [Archetype.INNOVATION_CATALYST, Archetype.ALCHEMIST],
    changemakeLevel: ChangemakerLevel.LEVEL_7,
    organizationName: "OpenEnergy Commons Kft.",
    workingSectors: ["energia", "technológia", "helyi közösségek"],
    collaborationPreference: [
      "technikai fejlesztés",
      "pilot programok",
      "nyílt forráskód",
    ],
    rdgAreas: [
      "energiaközösségek",
      "decentralizált energia",
      "digitális köztér",
    ],
    enjoyDoing:
      "Prototípusokat építek, kódolok, és látom, ahogy a megoldás valódi közösséget teremt.",
    currentIntention:
      "Nyílt platform elindítása energiaközösségek önszervezéséhez.",
    primaryLanguage: "hu",
    spokenLanguages: ["hu", "en"],
    availability: "BUSY",
    seekingConnections: true,
    seekingCoFounders: true,
    seekingSupport: false,
    skills: [
      { skill: "szoftverfejlesztés", skillType: SkillType.OFFERED },
      { skill: "energiarendszer-tervezés", skillType: SkillType.OFFERED },
      { skill: "startup-menedzsment", skillType: SkillType.OFFERED },
      { skill: "nyílt forráskód", skillType: SkillType.OFFERED },
      { skill: "jogi tanácsadás", skillType: SkillType.SEEKING },
    ],
    values: ["innováció", "nyitottság", "fenntarthatóság", "decentralizáció"],
    interests: [
      "energiaátmenet",
      "open source",
      "közösségi technológia",
      "startup",
    ],
  },
  {
    name: "Molnár Réka",
    displayName: "Réka",
    pronouns: "ő/övé",
    emailSlug: "molnar.reka",
    bio: "Közpolitikai elemző és rendszerzavaró gondolkodó, aki a strukturális változáshoz szükséges eszközökön dolgozik. Szegedről koordinálja a dél-alföldi klímaadaptációs közpolitikai dialógusokat.",
    motto: "Nem elég a tünetet kezelni — meg kell érteni a rendszer logikáját.",
    website: "https://molnarreka.hu",
    city: "Szeged",
    region: "Csongrád-Csanád",
    latitude: 46.253,
    longitude: 20.1414,
    archetypes: [Archetype.SYSTEM_DISRUPTOR, Archetype.SENTINEL],
    changemakeLevel: ChangemakerLevel.LEVEL_8,
    organizationName: "Dél-alföldi Klímapolitikai Műhely",
    workingSectors: ["közpolitika", "kutatás", "klímaadaptáció"],
    collaborationPreference: [
      "policy-alkotás",
      "kutatás",
      "stratégiai gondolkodás",
    ],
    rdgAreas: [
      "klímaadaptáció",
      "mezőgazdasági rendszerek",
      "közpolitikai reform",
    ],
    enjoyDoing:
      "Rendszereket térképezek fel, tévhiteket leplezek le, és jobb kérdéseket teszek fel.",
    currentIntention:
      "Klímaadaptációs törvényi keretet szeretnék előkészíteni a déli régió számára.",
    primaryLanguage: "hu",
    spokenLanguages: ["hu", "en", "de"],
    availability: "AVAILABLE",
    seekingConnections: true,
    seekingCoFounders: false,
    seekingSupport: true,
    skills: [
      { skill: "rendszerelemzés", skillType: SkillType.OFFERED },
      { skill: "közpolitikai kutatás", skillType: SkillType.OFFERED },
      { skill: "adat-analitika", skillType: SkillType.OFFERED },
      {
        skill: "érvelés és kritikus gondolkodás",
        skillType: SkillType.OFFERED,
      },
      { skill: "hálózatépítés", skillType: SkillType.SEEKING },
    ],
    values: [
      "igazságosság",
      "kritikus gondolkodás",
      "átláthatóság",
      "rendszerszemlélet",
    ],
    interests: [
      "közpolitika",
      "rendszerkritika",
      "klímaadaptáció",
      "politikatudomány",
    ],
  },
  {
    name: "Tóth Gábor",
    displayName: "Gábor",
    pronouns: "ő/övé",
    emailSlug: "toth.gabor",
    bio: "Üzleti stratéga és changemaker-mentor, aki zöld és szociális vállalkozásokat segít skálázni. Kecskemétről számos alföldi startup növekedési útját kísérte végig az ötlettől a piaci jelenlétig.",
    motto: "A jó stratégia nem a jövőt tervezi — hanem megteremti.",
    website: "https://tothgabor.hu",
    city: "Kecskemét",
    region: "Bács-Kiskun",
    latitude: 46.9063,
    longitude: 19.6926,
    archetypes: [Archetype.STRATEGIC_ADVISOR, Archetype.KEYSTONE],
    changemakeLevel: ChangemakerLevel.LEVEL_6,
    organizationName: "Impact Growth Tanácsadó",
    workingSectors: ["vállalkozásfejlesztés", "mentorlás", "hatásmérés"],
    collaborationPreference: [
      "mentorálás",
      "stratégiai tanácsadás",
      "befektetői bemutatók",
    ],
    rdgAreas: [
      "impakt vállalkozások",
      "helyi gazdaságfejlesztés",
      "mérési keretrendszerek",
    ],
    enjoyDoing:
      "Embereket és szervezeteket segítek megtalálni a legtöbb hatással bíró utat.",
    currentIntention:
      "Alföldi impakt vállalkozások számára mentorprogramot indítok.",
    primaryLanguage: "hu",
    spokenLanguages: ["hu", "en"],
    availability: "AVAILABLE",
    seekingConnections: true,
    seekingCoFounders: false,
    seekingSupport: false,
    skills: [
      { skill: "üzleti stratégia", skillType: SkillType.OFFERED },
      { skill: "mentorlás", skillType: SkillType.OFFERED },
      { skill: "hatásmérés", skillType: SkillType.OFFERED },
      { skill: "befektetői kapcsolatok", skillType: SkillType.OFFERED },
      { skill: "szoftverfejlesztés", skillType: SkillType.SEEKING },
    ],
    values: ["felelősség", "hosszú táv", "hatás", "hitelesség"],
    interests: [
      "impakt befektetés",
      "vállalkozásfejlesztés",
      "mérés",
      "coaching",
    ],
  },
  {
    name: "Papp Katalin",
    displayName: "Kata",
    pronouns: "ő/övé",
    emailSlug: "papp.katalin",
    bio: "Waldorf-pedagógus és közösségi oktatási innovátor, aki az egri régióban alternatív tanulási tereket teremt gyerekek és szülők számára. Saját erdei iskolát vezet, és pedagógusokat képez.",
    motto: "Az oktatás nem az iskolában kezdődik és nem ott ér véget.",
    website: "https://erdeiiskola-eger.hu",
    city: "Eger",
    region: "Heves",
    latitude: 47.9025,
    longitude: 20.3772,
    archetypes: [
      Archetype.LOCAL_PRACTITIONER,
      Archetype.NETWORK_WEAVER,
      Archetype.ECHO,
    ],
    changemakeLevel: ChangemakerLevel.LEVEL_5,
    organizationName: "Erdei Iskola Egyesület",
    workingSectors: ["oktatás", "gyerekek és ifjúság", "alternatív pedagógia"],
    collaborationPreference: [
      "oktatási projektek",
      "pedagógusképzés",
      "közösségépítés",
    ],
    rdgAreas: [
      "ökológiai oktatás",
      "közösségi tanulás",
      "természetközeli nevelés",
    ],
    enjoyDoing:
      "Gyerekekkel a természetben tanulok, és pedagógusokat kísérlek a saját útjukon.",
    currentIntention:
      "Erdei pedagógiai hálózatot szeretnék kiépíteni Észak-Magyarországon.",
    primaryLanguage: "hu",
    spokenLanguages: ["hu", "en", "de"],
    availability: "AVAILABLE",
    seekingConnections: true,
    seekingCoFounders: true,
    seekingSupport: false,
    skills: [
      { skill: "waldorf-pedagógia", skillType: SkillType.OFFERED },
      { skill: "erdei iskola-módszertan", skillType: SkillType.OFFERED },
      { skill: "pedagógusképzés", skillType: SkillType.OFFERED },
      { skill: "közösségépítés", skillType: SkillType.OFFERED },
      { skill: "pályázatírás", skillType: SkillType.SEEKING },
    ],
    values: [
      "gyermekközpontúság",
      "természet",
      "kreativitás",
      "közösség",
      "lassulás",
    ],
    interests: [
      "alternatív pedagógia",
      "természetközeli nevelés",
      "közösségi oktatás",
      "erdő",
    ],
  },
  {
    name: "Fekete Dávid",
    displayName: "Dávid",
    pronouns: "ő/övé",
    emailSlug: "fekete.david",
    bio: "Regeneratív mezőgazdasági szakértő és innovációs katalizátor, aki a tiszántúli gazdákat segíti átállni a talajregenerációs gazdálkodásra. Kísérletező farm-hálózatot épít Nyíregyháza körül.",
    motto: "Ha a talaj él, minden él — ha a talaj meghal, minden meghal.",
    website: "https://regenerativfarmer.hu",
    city: "Nyíregyháza",
    region: "Szabolcs-Szatmár-Bereg",
    latitude: 47.9495,
    longitude: 21.7244,
    archetypes: [
      Archetype.NETWORK_WEAVER,
      Archetype.INNOVATION_CATALYST,
      Archetype.TIDE,
    ],
    changemakeLevel: ChangemakerLevel.LEVEL_6,
    organizationName: "Tiszántúli Regeneratív Farmerek Szövetsége",
    workingSectors: ["mezőgazdaság", "talajregeneráció", "vidékfejlesztés"],
    collaborationPreference: [
      "kísérleti programok",
      "gazda-hálózatok",
      "tudáscsere",
    ],
    rdgAreas: ["regeneratív mezőgazdaság", "vízgazdálkodás", "biodiverzitás"],
    enjoyDoing:
      "Kísérletezem a talajon, megosztom a tanulságokat és gazdákat kapcsolok össze.",
    currentIntention:
      "Tiszántúli gazdahálózatot építek, amely megosztja a regeneratív módszereket.",
    primaryLanguage: "hu",
    spokenLanguages: ["hu", "en"],
    availability: "AVAILABLE",
    seekingConnections: true,
    seekingCoFounders: true,
    seekingSupport: true,
    skills: [
      { skill: "regeneratív gazdálkodás", skillType: SkillType.OFFERED },
      { skill: "talajbiológia", skillType: SkillType.OFFERED },
      { skill: "gazdahálózatok szervezése", skillType: SkillType.OFFERED },
      { skill: "vízgazdálkodás", skillType: SkillType.EXPERIENCE },
      { skill: "digitális platformok", skillType: SkillType.SEEKING },
    ],
    values: ["talaj", "regeneráció", "közösség", "türelem", "kísérletezés"],
    interests: [
      "talajbiológia",
      "regeneratív mezőgazdaság",
      "vidékfejlesztés",
      "vízgazdálkodás",
    ],
  },
];
